server {
    listen 80;
    server_name projectaptechka.space www.projectaptechka.space;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name projectaptechka.space www.projectaptechka.space;

    ssl_certificate /etc/letsencrypt/live/projectaptechka.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/projectaptechka.space/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
