create table if not exists public.mobile_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expo_push_token text not null,
  project_id text,
  platform text not null default 'android',
  device_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists mobile_push_tokens_expo_push_token_key
  on public.mobile_push_tokens (expo_push_token);

create index if not exists mobile_push_tokens_user_id_idx
  on public.mobile_push_tokens (user_id);

alter table public.mobile_push_tokens enable row level security;

drop policy if exists "Users can read own mobile push tokens" on public.mobile_push_tokens;
create policy "Users can read own mobile push tokens"
  on public.mobile_push_tokens
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own mobile push tokens" on public.mobile_push_tokens;
create policy "Users can insert own mobile push tokens"
  on public.mobile_push_tokens
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own mobile push tokens" on public.mobile_push_tokens;
create policy "Users can update own mobile push tokens"
  on public.mobile_push_tokens
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own mobile push tokens" on public.mobile_push_tokens;
create policy "Users can delete own mobile push tokens"
  on public.mobile_push_tokens
  for delete
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.mobile_push_tokens to authenticated;

do $$
begin
  if to_regclass('public.mobile_push_tokens_id_seq') is not null then
    grant usage, select on sequence public.mobile_push_tokens_id_seq to authenticated;
  end if;
end
$$;

create or replace function public.set_mobile_push_tokens_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_mobile_push_tokens_updated_at on public.mobile_push_tokens;
create trigger set_mobile_push_tokens_updated_at
before update on public.mobile_push_tokens
for each row
execute function public.set_mobile_push_tokens_updated_at();
